services:
  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
    networks:
      - app_net

networks:
  app_net:
    external: true
    name: docker-prod_app_net
